name: Sincronizar Docs para Wiki

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout do repositório principal
        uses: actions/checkout@v4

      - name: Sincronizar com a Wiki
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.wiki.git wiki

          find wiki/ -name "*.md" -delete

          cp -r docs/* wiki/

          cd wiki
          git add .
          git diff --staged --quiet || git commit -m "docs: sync wiki [ref: ${{ github.sha }}]" && git push
